// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIVa4O9cO0ohvt_76WeH-WhzksNKC8cjU',
    appId: '1:866527047399:web:b857e0fbdffd38edfebc42',
    messagingSenderId: '866527047399',
    projectId: 'flutter-f1c68',
    authDomain: 'flutter-f1c68.firebaseapp.com',
    databaseURL: 'https://flutter-f1c68-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-f1c68.firebasestorage.app',
    measurementId: 'G-G4RTDGV510',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9fJfwH4Fwnx77pBIDbwdaNHiUx8ErC0o',
    appId: '1:866527047399:android:90aa8419b034d204febc42',
    messagingSenderId: '866527047399',
    projectId: 'flutter-f1c68',
    databaseURL: 'https://flutter-f1c68-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-f1c68.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoSBs06uJU8POEpF3J2ct5scuAgO1zcoA',
    appId: '1:866527047399:ios:9a055439c35bca06febc42',
    messagingSenderId: '866527047399',
    projectId: 'flutter-f1c68',
    databaseURL: 'https://flutter-f1c68-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-f1c68.firebasestorage.app',
    iosClientId: '866527047399-nelgmn9u134mor3fqbvq897o0vpkn2k0.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoSBs06uJU8POEpF3J2ct5scuAgO1zcoA',
    appId: '1:866527047399:ios:9a055439c35bca06febc42',
    messagingSenderId: '866527047399',
    projectId: 'flutter-f1c68',
    databaseURL: 'https://flutter-f1c68-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-f1c68.firebasestorage.app',
    iosClientId: '866527047399-nelgmn9u134mor3fqbvq897o0vpkn2k0.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIVa4O9cO0ohvt_76WeH-WhzksNKC8cjU',
    appId: '1:866527047399:web:6e839ace918f295ffebc42',
    messagingSenderId: '866527047399',
    projectId: 'flutter-f1c68',
    authDomain: 'flutter-f1c68.firebaseapp.com',
    databaseURL: 'https://flutter-f1c68-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-f1c68.firebasestorage.app',
    measurementId: 'G-778NLFS7SS',
  );
}
